{
 "title": "K3s Node and Pod Monitoring",
 "description": "Monitors CPU, memory, networking and processes for all nodes and individual K3s pods",
 "tags": [
  "prometheus",
  "k3s",
  "pod",
  "node"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Node", "label": "Cluster Node", "query": { "query": "label_values(node)" } },
   { "name": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "description": "K3s cluster nodes",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<table style=\"height: 100%; width: 100%; background-color: rgb( 31 , 96 , 196 , 0.2);\">\n  <tbody style=\"border-bottom: 2px solid royalblue; border-top: 2px solid royalblue; letter-spacing: 1px; text-align: center;\">\n    <tr>\n      <td>\n        <h1><b><div style=\"margin-top: 10px;\">Nodes</div></b></h1>\n      </td>\n    </tr>\n    <tr style=\"margin-top: -10px;\">\n      <td>\n      Oneplus6: Octa-core, 8GB Ram, 128GB\n      </td>\n    </tr>\n  </tbody>\n</table>"
   }
  },
  {
   "title": "Cluster memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{node=~\"^$Node$\"} - node_memory_MemFree_bytes{node=~\"^$Node$\"}  - node_memory_Buffers_bytes{node=~\"^$Node$\"} - node_memory_Cached_bytes{node=~\"^$Node$\"}) / node_memory_MemTotal_bytes{node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",instance=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{instance=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{id=\"/\",instance=~\"^$Node$\"}) / sum (container_fs_limit_bytes{id=\"/\",instance=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{node=~\"^$Node$\"} - node_memory_MemFree_bytes{node=~\"^$Node$\"}  - node_memory_Buffers_bytes{node=~\"^$Node$\"} - node_memory_Cached_bytes{node=~\"^$Node$\"}))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"^$Node$\"}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",instance=~\"^$Node$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "machine_cpu_physical_cores" }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{id=\"/\",instance=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{id=\"/\",instance=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"^$Node$\"} - node_memory_MemFree_bytes{node=~\"^$Node$\"} - node_memory_Buffers_bytes{node=~\"^$Node$\"} - node_memory_Cached_bytes{node=~\"^$Node$\"}",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{node=~\"^$Node$\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{node=~\"^$Node$\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=~\"^$Node$\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_load1{node=~\"^$Node$\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{node=~\"^$Node$\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{node=~\"^$Node$\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Total CPU usage (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",instance=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{instance=~\"^$Node$\"}) * 1",
     "legendFormat": "all pods"
    }
   ]
  },
  {
   "title": "Idle CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", node=~\"^$Node$\"}[5m])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (rate(node_nfsd_disk_bytes_read_total{node=~\"^$Node$\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (node) (rate(node_nfsd_disk_bytes_written_total{node=~\"^$Node$\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (node) (rate(node_disk_io_time_seconds_total{node=~\"^$Node$\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{instance=~\"^$Node$\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{instance=~\"^$Node$\"}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{node=~\"^$Node$\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{node=~\"^$Node$\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "type": "text",
   "description": "K3s cluster npods",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 46 },
   "options": {
    "content": "<table style=\"height: 100%; width: 100%; background-color: rgb( 31 , 96 , 196 , 0.2);\">\n  <tbody style=\"border-bottom: 2px solid royalblue; border-top: 2px solid royalblue; letter-spacing: 1px; text-align: center;\">\n    <tr>\n      <td>\n        <h1><b><div style=\"margin-top: 10px;\">Pods</div></b></h1>\n      </td>\n    </tr>\n    <tr style=\"margin-top: -10px;\">\n      <td>\n      Pod usage by namespace\n      </td>\n    </tr>\n  </tbody>\n</table>"
   }
  },
  {
   "title": "CPU use by namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(container_cpu_usage_seconds_total{pod!=\"\", instance=~\"^$Node$\", namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{ namespace}}"
    }
   ]
  },
  {
   "title": "Memory use by namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod!=\"\", instance=~\"^$Node$\",namespace=~\"$Namespace\"}) by (namespace)",
     "legendFormat": "{{ namespace}}"
    }
   ]
  },
  {
   "title": "Pod CPU usage (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod!=\"\",instance=~\"^$Node$\",namespace=~\"$Namespace\"}[5m])) by (pod)",
     "legendFormat": "pod: {{ pod }}"
    }
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod!=\"\",instance=~\"^$Node$\",namespace=~\"$Namespace\"}) by (pod)",
     "legendFormat": "pod: {{ pod }} | {{ container_name }}"
    }
   ]
  },
  {
   "title": "All processes CPU usage (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",instance=~\"^$Node$\",namespace=~\"$Namespace\"}[5m])) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "All processes memory usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",instance=~\"^$Node$\",namespace=~\"$Namespace\"}) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  }
 ]
}