{
 "title": "Network Monitoring",
 "description": "Monitors HTTP requests, DNS queries and ICMP (RTT, latency, packet loss)",
 "tags": [
  "icmp",
  "influxdb",
  "telegraf",
  "network",
  "dns",
  "http"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "SHOW TAG VALUES FROM \"ping\" WITH KEY = \"host\""
   },
   {
    "name": "host",
    "label": "Ping Host",
    "query": "SHOW TAG VALUES WITH KEY = \"url\""
   }
  ]
 },
 "panels": [
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Requests Response Times",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Requests Response Code",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "http_response_code" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Response code" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Ping Combined Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Average Ping response times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "average response" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "url::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Ping packet loss (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "packet loss" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "url::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Ping packets Transmitted vs Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_url: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "packets_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "packets received" ], "type": "alias" }
      ],
      [
       { "params": [ "packets_transmitted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "packets trasmitted" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "url::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "DNS Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Google DNS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dns_query",
     "select": [
      [
       { "params": [ "rcode_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server::tag", "operator": "=", "value": "8.8.8.8" }
     ]
    }
   ]
  },
  {
   "title": "Cloudflare DNS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dns_query",
     "select": [
      [
       { "params": [ "rcode_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server::tag", "operator": "=", "value": "1.1.1.1" }
     ]
    }
   ]
  },
  {
   "title": "DNS query time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "query": "SELECT last(\"query_time_ms\") FROM \"dns_query\" WHERE (\"host\"::tag =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"server\"::tag fill(null)",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Ping per Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Ping $host",
   "type": "timeseries",
   "description": "Ping test towards $host",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "maximum_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "url::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "minimum_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "url::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "url::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "package loss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "url::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}