{
 "title": "Prometheus Scraping",
 "description": "Scrape instances and times for troubleshooting prometheus metric collection",
 "tags": [
  "prometheus",
  "scrape"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "label_values(up, job)" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(up{job='$job'}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Scrape times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "SD  Instance/Job",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum (up) by (job)" }
   ]
  },
  {
   "title": "Scrape Rt/Job",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (scrape_duration_seconds) by (job)"
    }
   ]
  },
  {
   "title": "Scrape Rt ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "-sum (up)" },
    { "expr": "sum (scrape_duration_seconds)" }
   ]
  },
  {
   "title": "Scrape Sample",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum (scrape_samples_scraped)" },
    {
     "expr": "-sum (scrape_samples_post_metric_relabeling)"
    }
   ]
  },
  {
   "title": "Scrape Rt / instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (scrape_duration_seconds{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Scrape Rt / instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (scrape_duration_seconds{job=\"$job\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Scrape Sample Total / Job",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (scrape_samples_scraped) by (job)"
    }
   ]
  },
  {
   "title": "Scrape Relabel Sample Total / Job",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (scrape_samples_post_metric_relabeling) by (job)"
    }
   ]
  },
  {
   "title": "Scrape Sample Total / instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (scrape_samples_scraped{job='$job'}) by (instance)"
    }
   ]
  },
  {
   "title": "Scrape Relabel Sample Total / Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (scrape_samples_post_metric_relabeling{job='$job'}) by (instance)"
    }
   ]
  },
  {
   "title": "Total Series Add / Job",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(scrape_series_added) by (job)"
    }
   ]
  },
  {
   "title": "Total Series Add / Instance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (scrape_series_added{job='$job'}) by (instance)"
    }
   ]
  },
  {
   "title": "SD  Instance/Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum (up) by (job)" }
   ]
  },
  {
   "title": "Scrape Rt/Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (scrape_duration_seconds) by (job)"
    }
   ]
  }
 ]
}