{
 "title": "Teltonika Dashboard",
 "description": "Monitors CPU, load, signal and traffic for Teltonika RUT950 4G WiFi router",
 "tags": [
  "teltonika",
  "network",
  "prometheus",
  "snap-exporter"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(ifInOctets,job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mImei{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Signal ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mSignal{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Signal level"
    },
    {
     "expr": "mSINR{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "LTE SINR level"
    },
    {
     "expr": "mRSRP{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "LTE RSRP level"
    },
    {
     "expr": "mRSRQ{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "LTE RSRQ level"
    }
   ]
  },
  {
   "title": "Conn. Status",
   "type": "stat",
   "description": "Connection Status",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mConnectionState{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{mConnectionState}}"
    }
   ]
  },
  {
   "title": "Operator",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mOperator{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{mOperator}}"
    }
   ]
  },
  {
   "title": "Conn. Uptime",
   "type": "stat",
   "description": "Connection Uptime",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "connectionUptime{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Reg. Status",
   "type": "stat",
   "description": "Registration Status",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mNetState{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{mNetState}}"
    }
   ]
  },
  {
   "title": "Signal",
   "type": "gauge",
   "description": "Received signal strength indication",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mSignal{instance=\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "RSRP",
   "type": "gauge",
   "description": "Reference Signal Received Power",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mRSRP{instance=\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "RSRQ",
   "type": "gauge",
   "description": "Reference Signal Received Quality",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mRSRQ{instance=\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "SINR",
   "type": "gauge",
   "description": "Signal to Interference plus Noise Ratio",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mSINR{instance=\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-ssCpuIdle{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load (1m avg)",
   "type": "gauge",
   "description": "Sysload (1m avg)",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "laLoadFloat{instance=\"$instance\", job=\"$job\", laIndex=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load (5m avg)",
   "type": "gauge",
   "description": "Sysload (5m avg)",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "laLoadFloat{instance=\"$instance\", job=\"$job\", laIndex=\"2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load (15m avg)",
   "type": "gauge",
   "description": "Sysload (15m avg)",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "laLoadFloat{instance=\"$instance\", job=\"$job\", laIndex=\"3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flash Used",
   "type": "gauge",
   "description": "Used flash memory",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrStorageUsed{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"/\"}/hrStorageSize{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temp FS",
   "type": "gauge",
   "description": "Used flash memory",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrStorageUsed{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"/tmp\"}/hrStorageSize{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"/tmp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "RAM memory used",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(memAvailReal{instance=\"$instance\",job=\"$job\"}/memTotalReal{instance=\"$instance\",job=\"$job\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Modem Temp",
   "type": "gauge",
   "description": "Temperature",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mTemperature{instance=\"$instance\", job=~\"$job\"}/10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Out / In",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$job\",instance=\"$instance\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "-irate(ifHCInOctets{job=\"$job\",instance=\"$instance\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Conn. Type",
   "type": "stat",
   "description": "Connection Type",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mNetworkType{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{mNetworkType}}"
    }
   ]
  },
  {
   "title": "Flash Used",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrStorageAllocationUnits{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"/\"}*hrStorageUsed{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"/\"}"
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "stat",
   "description": "Mem Used",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrStorageAllocationUnits{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"Physical memory\"}*hrStorageUsed{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"Physical memory\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Sys. Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrSystemUptime{instance=\"$instance\",job=\"$job\"}/100"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "description": "# of Cores",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssCpuNumCpus{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Flash Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrStorageAllocationUnits{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"/\"}*hrStorageSize{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"/\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memTotalReal{instance=\"$instance\",job=\"$job\"}*1024"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memTotalSwap{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100-ssCpuIdle{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "% CPU {{instance}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "hrStorageSize{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"Physical memory\"}*hrStorageAllocationUnits{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"Physical memory\"}",
     "legendFormat": "Memory Size"
    },
    {
     "expr": "hrStorageAllocationUnits{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"Physical memory\"}*hrStorageUsed{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"Physical memory\"}",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "mTemperature{instance=\"$instance\", job=~\"$job\"}/10",
     "legendFormat": "Temperature {{instance}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 21, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "deviceName{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fwVersion{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hardwareRevision{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mConnectionState{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mICCID{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mIMSI{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mIP{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mImei{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mManufacturer{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mModel{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mNetState{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mNetworkType{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mOperatorNumber{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mPinState{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mRevision{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mSerial{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "serial{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mCellID{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mOperator{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "batchNumber{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}