{
 "title": "Victron Dashboard",
 "description": "Uses Cerbo GX to monitor Victron MPPT solar, Multiplus inverter, DC usage, batteries, tanks, and Ruuvi temperture sensors",
 "tags": [
  "victron",
  "influxdb",
  "telegraf",
  "cerbo",
  "mqtt",
  "ruuvi"
 ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cerbo",
    "query": {
     "query": "SHOW TAG VALUES FROM \"N\" WITH KEY = \"cerbo\""
    }
   }
  ]
 },
 "panels": [
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "N",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "text",
   "description": "Victron Energy  \nSmart Shunt 500A/50mV\n",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "options": {
    "content": "<table style=\"height: 100%; width: 100%; background-color: rgb( 31 , 96 , 196 , 0.2);\">\n  <tbody style=\"border-bottom: 2px solid royalblue; border-top: 2px solid royalblue; letter-spacing: 1px; text-align: center;\">\n    <tr>\n      <td>\n        <h1><b><div style=\"margin-top: 10px;\">Battery</div></b></h1>\n      </td>\n    </tr>\n    <tr style=\"margin-top: -10px;\">\n      <td>\n        3 x 170Ah AGM parallel = 510Ah = 6120Wh at 12V\n      </td>\n    </tr>\n  </tbody>\n</table>"
   }
  },
  {
   "type": "gauge",
   "description": "Current state of charge (SOC) of the leisure batteries, \ndetermined by the measuring resistor.",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SOC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "N",
     "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'system' AND \"topic\"::tag = 'Dc/Battery/Soc') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path::tag", "operator": "=", "value": "system" },
      { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Dc/Battery/Soc" }
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "SOC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "N",
     "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'system' AND \"topic\"::tag = 'Dc/Battery/Soc') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "path::tag", "operator": "=", "value": "system" },
      { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Dc/Battery/Soc" }
     ]
    },
    {
     "alias": "Watt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "N",
     "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'system' AND \"topic\"::tag = 'Dc/Battery/Voltage') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "path::tag", "operator": "=", "value": "system" },
      { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Dc/Battery/Power" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "Remaining runtime at current consumption,\ncalculated from the measuring resistor.",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Seconds",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "system/Dc/Battery/TimeToGo",
     "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'system' AND \"topic\"::tag = 'Dc/Battery/TimeToGo') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "Current voltage of the leisure batteries,\nmeasured at the measuring resistor in volts.",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Volt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "N",
     "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'system' AND \"topic\"::tag = 'Dc/Battery/Voltage') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path::tag", "operator": "=", "value": "system" },
      { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Dc/Battery/Voltage" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "Current current flow of the leisure batteries,\nmeasured at the measuring resistor in amperes.\n(Positive values: charge, negative values: consumption)",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Ampere",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "system/Dc/Battery/Current",
     "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'system' AND \"topic\"::tag = 'Dc/Battery/Current') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "Current power of the leisure batteries measured in watts (Positive values: charge, negative values: discharge)",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Watt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "system/Dc/System/Power",
     "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'system' AND \"topic\"::tag = 'Dc/Battery/Power') AND $timeFilter GROUP BY time($__interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "Current temperature of the leisure batteries, measured by a temperature sensor via the inverter.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "vebus/Dc/0/Temperature",
     "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'vebus' AND \"topic\"::tag = 'Dc/0/Temperature') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltage and Current",
   "type": "timeseries",
   "description": "Battery voltage and current curve, measured by the measuring resistor in volts and amperes.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Volt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system/Dc/Battery/Voltage",
     "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'system' AND \"topic\"::tag = 'Dc/Battery/Voltage') AND $timeFilter GROUP BY time($__interval) fill(none)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Ampere",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system/Dc/Battery/Current",
     "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'system' AND \"topic\"::tag = 'Dc/Battery/Current') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Battery temperature history, measured by a temperature sensor in degrees Celsius.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vebus/Dc/0/Temperature",
     "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'vebus' AND \"topic\"::tag = 'Dc/0/Temperature') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power ",
   "type": "timeseries",
   "description": "Battery power in Watts, positive is charge and negative discharge ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Watt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system/Dc/System/Power",
     "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'system' AND \"topic\"::tag = 'Dc/Battery/Power') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "description": "Victron Energy  \nSmart Solar Charger MPPT 100/30",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 179 },
     "options": {
      "content": "<table style=\"height: 100%; width: 100%; background-color: rgb( 31 , 96 , 196 , 0.2);\">\n  <tbody style=\"border-bottom: 2px solid royalblue; border-top: 2px solid royalblue; letter-spacing: 1px; text-align: center;\">\n    <tr>\n      <td>\n        <h1><b><div style=\"margin-top: 10px;\">Solar</div></b></h1>\n      </td>\n    </tr>\n    <tr style=\"margin-top: -10px;\">\n      <td>\n        2 x 200W, 1 x 130W in serial = 530W\n      </td>\n    </tr>\n  </tbody>\n</table>"
     }
    },
    {
     "title": "Power in Watts",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 316 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Watt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "N",
       "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'solarcharger' AND \"topic\"::tag = 'Yield/Power') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "solarcharger" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Yield/Power" }
       ]
      }
     ]
    },
    {
     "title": "Power Curve",
     "type": "timeseries",
     "description": "Solar module power curve, measured by the solar charge controller in watts.",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 316 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "alias": "Watt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "solarcharger/Yield/Power",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'solarcharger' AND \"topic\"::tag = 'Yield/Power') AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Status",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "solarcharger/State",
       "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'solarcharger' AND \"topic\"::tag = 'State') AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "Mode",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "N",
       "query": "SELECT last(\"value\") *2.5 FROM \"N\" WHERE (\"path\"::tag = 'solarcharger' AND \"topic\"::tag = 'MppOperationMode') AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "*2.5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "solarcharger" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "MppOperationMode" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "description": "Current voltage of the solar modules, measured by the solar charge controller in volts.",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 322 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Volt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "solarcharger/Pv/V",
       "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'solarcharger' AND \"topic\"::tag = 'Pv/V') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "description": "Current current flow of the solar modules, measured by the solar charge controller in amperes.",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 322 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Watt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "solarcharger/Yield/Power",
       "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'solarcharger' AND \"topic\"::tag = 'Yield/Power') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "Volt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "solarcharger/Pv/V",
       "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'solarcharger' AND \"topic\"::tag = 'Pv/V') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      { "expression": "$Watt / $Volt", "type": "math" }
     ]
    },
    {
     "type": "stat",
     "description": "Current status of the solar charge controller.",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 322 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Status",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "solarcharger/State",
       "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'solarcharger' AND \"topic\"::tag = 'State') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Solarpanel",
     "type": "timeseries",
     "description": "Voltage and current curve of the solar modules, measured by the solar charge controller in volts and amperes.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 325 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "alias": "Volt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "solarcharger/Pv/V",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'solarcharger' AND \"topic\"::tag = 'Pv/V') AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Status",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "N",
       "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'solarcharger' AND \"topic\"::tag = 'State') AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "solarcharger" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "State" }
       ]
      },
      {
       "alias": "Watt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "N",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'solarcharger' AND \"topic\"::tag = 'Yield/Power') AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "solarcharger" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Yield/Power" }
       ]
      },
      { "expression": "$Watt / $Volt", "type": "math" }
     ]
    },
    {
     "title": "Battery",
     "type": "timeseries",
     "description": "Battery voltage and current curves, measured by the solar charge controller in volts and amperes.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 332 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "alias": "Volt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "solarcharger/Dc/0/Voltage",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'solarcharger' AND \"topic\"::tag = 'Dc/0/Voltage') AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Ampere",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "solarcharger/Dc/0/Current",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'solarcharger' AND \"topic\"::tag = 'Dc/0/Current') AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Status",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "solarcharger/State",
       "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'solarcharger' AND \"topic\"::tag = 'State') AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DC power usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "description": "From other dashboards",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 180 },
     "options": {
      "content": "<table style=\"height: 100%; width: 100%; background-color: rgb( 31 , 96 , 196 , 0.2);\">\n  <tbody style=\"border-bottom: 2px solid royalblue; border-top: 2px solid royalblue; letter-spacing: 1px; text-align: center;\">\n    <tr>\n      <td>\n        <h1><b><div style=\"margin-top: 10px;\">DC power</div></b></h1>\n      </td>\n    </tr>\n    <tr style=\"margin-top: -10px;\">\n      <td>\n      Usage\n      </td>\n    </tr>\n  </tbody>\n</table>\n"
     }
    },
    {
     "title": "DC power",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 273 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Watt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "N",
       "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'system' AND \"topic\"::tag = 'Dc/System/Power') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "system" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "select tag value" }
       ]
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "Battery DC load curve, measured by the measuring resistor in watts.",
     "gridPos": { "h": 9, "w": 18, "x": 6, "y": 273 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "alias": "Watt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "system/Dc/System/Power",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'system' AND \"topic\"::tag = 'Dc/System/Power') AND $timeFilter GROUP BY time($__interval) fill(none)\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Current",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 282 },
     "fieldConfig": { "defaults": { "unit": "voltamp" } },
     "targets": [
      {
       "alias": "Volt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "N",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'solarcharger' AND \"topic\"::tag = 'Pv/V') AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "system" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Dc/Battery/Voltage" }
       ]
      },
      {
       "alias": "Watt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "N",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'system' AND \"topic\"::tag = 'Dc/System/Power') AND $timeFilter GROUP BY time($__interval) fill(none)\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "solarcharger" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Yield/Power" }
       ]
      },
      { "expression": "$Watt / $Volt", "type": "math" }
     ]
    }
   ]
  },
  {
   "title": "Inverter Output",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "description": "Victron Energy  \nMultiPlus Compact 12/2000/80-30",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 181 },
     "options": {
      "content": "<table style=\"height: 100%; width: 100%; background-color: rgb( 31 , 96 , 196 , 0.2);\">\n  <tbody style=\"border-bottom: 2px solid royalblue; border-top: 2px solid royalblue; letter-spacing: 1px; text-align: center;\">\n    <tr>\n      <td>\n        <h1><b><div style=\"margin-top: 10px;\">Inverter</div></b></h1>\n      </td>\n    </tr>\n    <tr style=\"margin-top: -10px;\">\n      <td>\n        Output and Input\n      </td>\n    </tr>\n  </tbody>\n</table>"
     }
    },
    {
     "title": "AC power",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 231 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Watt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "N",
       "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'vebus' AND \"topic\"::tag = 'Ac/Out/L1/P') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "vebus" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Ac/Out/L1/P" }
       ]
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 231 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "alias": "Watt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "N",
       "query": "SELECT mean(\"value\") FROM \"vebus/Ac/Out/L1/P\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "vebus" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Ac/Out/L1/P" }
       ]
      },
      {
       "alias": "Status",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "N",
       "query": "SELECT mean(\"value\") FROM \"vebus/Ac/Out/L1/P\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "vebus" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "State" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "description": "Current energy source of the inverter.",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 237 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Quelle",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "N",
       "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'vebus' AND \"topic\"::tag = 'Ac/ActiveIn/S') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "vebus" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Ac/ActiveIn/S" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "description": "Current current flow of the inverter.",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 237 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Ampere",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "N",
       "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'vebus' AND \"topic\"::tag = 'Ac/Out/L1/I') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "vebus" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Ac/Out/L1/I" }
       ]
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 240 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "alias": "Volt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "N",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'vebus' AND \"topic\"::tag = 'Ac/Out/L1/V') AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "vebus" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Ac/Out/L1/V" }
       ]
      },
      {
       "alias": "Ampere",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "N",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'vebus' AND \"topic\"::tag = 'Ac/Out/L1/I') AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "vebus" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Ac/Out/L1/I" }
       ]
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 247 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Watt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "N",
       "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'vebus' AND \"topic\"::tag = 'Ac/ActiveIn/L1/P') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "vebus" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Ac/ActiveIn/L1/P" }
       ]
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 247 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "alias": "Watt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "N",
       "query": "SELECT mean(\"value\") FROM \"vebus/Ac/ActiveIn/P\" WHERE $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "vebus" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Ac/ActiveIn/L1/P" }
       ]
      },
      {
       "alias": "Status",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "N",
       "query": "SELECT last(\"value\") FROM \"vebus/Ac/ActiveIn/Connected\" WHERE $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "vebus" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Ac/ActiveIn/Connected" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "description": "\nCurrent input voltage of the inverter, measured in volts.",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 253 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Volt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "N",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "vebus" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Ac/ActiveIn/L1/V" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "description": "Current input current flow of the inverter\nmeasured in amperes.",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 253 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Ampere",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "N",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "vebus" },
        {
         "condition": "AND",
         "key": "topic::tag",
         "operator": "=",
         "value": "Ac/ActiveIn/CurrentLimitIsAdjustable"
        }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "description": "\nCurrent input current limit of the inverter, measured in amperes.",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 253 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Ampere",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "N",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "vebus" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Ac/In/1/CurrentLimit" }
       ]
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 256 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "alias": "Volt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "N",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "vebus" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Ac/ActiveIn/L1/V" }
       ]
      },
      {
       "alias": "Ampere",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "N",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "vebus" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Ac/ActiveIn/L1/I" }
       ]
      }
     ]
    },
    {
     "title": "AC PV Power by Installation",
     "type": "timeseries",
     "description": "From other dashboard",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 263 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "alias": "Watt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "system/Dc/System/Power",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'system' AND \"topic\"::tag = 'Ac/In/0/Source') AND $timeFilter GROUP BY time($__interval) fill(none)\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Tanks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "description": "Voltage tank meters using Victron GX tank 140",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 182 },
     "options": {
      "content": "<table style=\"height: 100%; width: 100%; background-color: rgb( 31 , 96 , 196 , 0.2);\">\n  <tbody style=\"border-bottom: 2px solid royalblue; border-top: 2px solid royalblue; letter-spacing: 1px; text-align: center;\">\n    <tr>\n      <td>\n        <h1><b><div style=\"margin-top: 10px;\">Tanks</div></b></h1>\n      </td>\n    </tr>\n    <tr style=\"margin-top: -10px;\">\n      <td>\n      200L diesel, 700L water\n      </td>\n    </tr>\n  </tbody>\n</table>"
     }
    },
    {
     "title": "Diesel",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 208 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "diesel",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "N",
       "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'tank' AND \"topic\"::tag = 'Level' AND \"VRMinstance\"::tag = '25') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "tank" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Level" },
        { "condition": "AND", "key": "VRMinstance::tag", "operator": "=", "value": "25" }
       ]
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 18, "x": 6, "y": 208 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Level",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "N",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'system' AND \"topic\"::tag = 'Dc/Battery/Soc') AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "tank" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Level" },
        { "condition": "AND", "key": "VRMinstance::tag", "operator": "=", "value": "25" }
       ]
      },
      {
       "alias": "Volt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "N",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'system' AND \"topic\"::tag = 'Dc/Battery/Voltage') AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "tank" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "RawValue" },
        { "condition": "AND", "key": "VRMinstance::tag", "operator": "=", "value": "25" }
       ]
      }
     ]
    },
    {
     "title": "Water",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 218 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "diesel",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "N",
       "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'tank' AND \"topic\"::tag = 'Level' AND \"VRMinstance\"::tag = '24') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "tank" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Level" },
        { "condition": "AND", "key": "VRMinstance::tag", "operator": "=", "value": "25" }
       ]
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 18, "x": 6, "y": 218 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Level",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "N",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'system' AND \"topic\"::tag = 'Dc/Battery/Soc') AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "tank" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Level" },
        { "condition": "AND", "key": "VRMinstance::tag", "operator": "=", "value": "24" }
       ]
      },
      {
       "alias": "Volt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "N",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'system' AND \"topic\"::tag = 'Dc/Battery/Voltage') AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "tank" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "RawValue" },
        { "condition": "AND", "key": "VRMinstance::tag", "operator": "=", "value": "24" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Temperature and Humidity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "description": "Ruuvi sensors blue toothed to MultiPlus",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 183 },
     "options": {
      "content": "<table style=\"height: 100%; width: 100%; background-color: rgb( 31 , 96 , 196 , 0.2);\">\n  <tbody style=\"border-bottom: 2px solid royalblue; border-top: 2px solid royalblue; letter-spacing: 1px; text-align: center;\">\n    <tr>\n      <td>\n        <h1><b><div style=\"margin-top: 10px;margin-bottom: -10px;\">Temperature and Humidity</div></b></h1>\n      </td>\n    </tr>\n    <tr style=\"margin-top: -10px;\">\n      <td>\n        Ruuvi Bluetooth-Sensor\n      </td>\n    </tr>\n  </tbody>\n</table>"
     }
    },
    {
     "title": "Galley",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Watt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "N",
       "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'temperature' AND \"topic\"::tag = 'Temperature' AND \"VRMinstance\"::tag = '20') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=", "value": "temperature" },
        { "condition": "AND", "key": "topic::tag", "operator": "=", "value": "Temperature" },
        { "condition": "AND", "key": "VRMinstance::tag", "operator": "=", "value": "20" }
       ]
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "Temperature, humidity, and voltage trends measured by the Bluetooth sensor in °C, %H, and volts.",
     "gridPos": { "h": 9, "w": 18, "x": 6, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Temperature",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "temperature/Temperature",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'temperature' AND \"topic\"::tag = 'Temperature' AND \"VRMinstance\"::tag = '20') AND  $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instanceNumber", "operator": "=", "value": "30" }
       ]
      },
      {
       "alias": "Volt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "temperature/BatteryVoltage",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'temperature' AND \"topic\"::tag = 'BatteryVoltage' AND \"VRMinstance\"::tag = '20') AND  $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instanceNumber", "operator": "=", "value": "30" }
       ]
      },
      {
       "alias": "Humidity",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "temperature/Humidity",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'temperature' AND \"topic\"::tag = 'Humidity' AND \"VRMinstance\"::tag = '20') AND  $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instanceNumber", "operator": "=", "value": "30" }
       ]
      }
     ]
    },
    {
     "title": "Bedroom",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 196 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Temperatur",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "temperature/Temperature",
       "query": "SELECT last(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'temperature' AND \"topic\"::tag = 'Temperature' AND \"VRMinstance\"::tag = '21') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "instanceNumber", "operator": "=", "value": "28" }
       ]
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "Temperature, humidity, and voltage trends measured by the Bluetooth sensor in °C, %H, and volts.",
     "gridPos": { "h": 9, "w": 18, "x": 6, "y": 196 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Temperature",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "temperature/Temperature",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'temperature' AND \"topic\"::tag = 'Temperature' AND \"VRMinstance\"::tag = '21') AND  $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instanceNumber", "operator": "=", "value": "28" }
       ]
      },
      {
       "alias": "Volt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "temperature/BatteryVoltage",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'temperature' AND \"topic\"::tag = 'BatteryVoltage' AND \"VRMinstance\"::tag = '21') AND  $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instanceNumber", "operator": "=", "value": "28" }
       ]
      },
      {
       "alias": "Humidity",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "temperature/Humidity",
       "query": "SELECT mean(\"value\") FROM \"N\" WHERE (\"path\"::tag = 'temperature' AND \"topic\"::tag = 'Humidity' AND \"VRMinstance\"::tag = '21') AND  $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instanceNumber", "operator": "=", "value": "28" }
       ]
      }
     ]
    }
   ]
  }
 ]
}